config/routes.rb
Rails.application.routes.draw do

  root 'home#index'
  
  get "home/blog" => "home#blog"
  get "home/list" => "home#list"
  get "home/content" => "home#content"
  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def list
        
    end
    
    def blog
        
    end
    
    def content
        
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/blog.html.erb
<!DOCTYPE html>
<html>

<body>
	<div style="width:800px; height:410px; margin:0px auto; background-image: url(http://cdn.ypcall.com/users/B0076044-C51B-4445-BA56-2928EC583EA8/drive/media/bg.png); border-radius: 10px; font-family: Microsoft JhengHei ">
		<a href="">
			</br>
			<div style="margin-left: 50px; margin-right: 50px; ">
			<h2>阿公的香水檸檬──從一顆檸檬看見友善土地的價值</h2>
			</div>
			<div style="text-align: center">
				<img style="width:700px;" src="https://scontent-tpe1-1.xx.fbcdn.net/v/t1.0-9/11218901_969818003079885_4740449858505874150_n.png?oh=396f3e99efe192961949ce6f36928f89&oe=579DC10D">
	        </div>			
		</a>
		<div style="margin-left: 50px; margin-right: 50px;">
		</br>
			由阿公的孫子們組成的團隊，希望能藉由研發的檸檬系列商品，將阿公天然的檸檬分享給更多人，更期待可以因此讓大家在生活裡，更在意自己吃進身體的東西，用好的食物給身體美好的力量......
		<p style="float: right">
			<
			<a href="">了解更多</a>
			>
		</p>   
		</div>
	</div>
	</br>
	<div style="width:800px; height:440px; margin:0px auto; background-image: url(http://cdn.ypcall.com/users/B0076044-C51B-4445-BA56-2928EC583EA8/drive/media/bg.png); border-radius: 10px; font-family: Microsoft JhengHei; ">
		<a href="">
			</br>
			<div style="margin-left: 50px; margin-right: 50px;">
			<h2>果醬女孩──果醬和你想像的不一樣</h2>
			</div>
			<div style="text-align: center">
				<img style="width:700px;" src="https://scontent-tpe1-1.xx.fbcdn.net/v/t34.0-12/13235839_1448649168494334_452861147_n.png?oh=797c513c9465f54ca85ff81af8249397&oe=573D5260">
	        </div>			
		</a>
		<div style="margin-left: 50px; margin-right: 50px;">
		</br>
			一位20歲的小女生，來自熱情的台南，喜歡烹飪的沛蓉，在一次因緣際會下，接觸到了自己製作的手工果醬，意外品嘗到令人感動與驚喜的美味，就帶著與人分享的心情，開始販售，一段故事就這樣開始了......
		<p style="float: right">
			<
			<a href="">了解更多</a>
			>
		</p> 
		</div>
	</div>
	</br>
	<div style="width:800px; height:385px; margin:0px auto; background-image: url(http://cdn.ypcall.com/users/B0076044-C51B-4445-BA56-2928EC583EA8/drive/media/bg.png); border-radius: 10px;font-family: Microsoft JhengHei ;" >
		<a href="">
			</br>
			<div style="margin-left: 50px; margin-right: 50px;">
			<h2>卡維蘭──來自於拉拉山的水蜜桃團隊</h2>
			</div>
			<div style="text-align: center">
				<img style="width:700px; " src="https://scontent-tpe1-1.xx.fbcdn.net/v/t34.0-12/13220112_1448644021828182_1643035697_n.png?oh=6347805ad8c8a42585d7c21e3e6c3da0&oe=573ECF9D">
	        </div>			
		</a>
		<div style="margin-left: 50px; margin-right: 50px;">
            </br>
            創辦人2014年從拉拉山上的高義國小退伍。在和村民相處的過程中發現了高義部落農民的問題，找到著力點後便找了一群志同道合的朋友，組成了「卡維蘭」團隊，幫助果農自產自銷水蜜桃......		
	    <p style="float: right">
			<
			<a href="">了解更多</a>
			>
		</p> 
		</div>
	</div>
	</br>
	<div style="width:800px; height:435px; margin:0px auto; background-image: url(http://cdn.ypcall.com/users/B0076044-C51B-4445-BA56-2928EC583EA8/drive/media/bg.png); border-radius: 10px; font-family: Microsoft JhengHei ;">
		<a href="">
			</br>
			<div style="margin-left: 50px; margin-right: 50px;">
			<h2>田玉軒──柳營小山村的忘憂果醬</h2>
			</div>
			<div style="text-align: center">
				<img style="width:700px;" src="https://scontent-tpe1-1.xx.fbcdn.net/v/t34.0-12/13245940_1448652115160706_1539561580_n.png?oh=9b1022abad58e0a6ee8f4531ed46bc4f&oe=573D8A5F">
	        </div>			
		</a>
		<div style="margin-left: 50px; margin-right: 50px;">
		</br>    
            男孩在東海大學畢業後，在台南柳營區生活環境純樸，感覺輕鬆愜意的山村─旭山村，希望能把果醬當作一個平台，彙集台灣各地達人種植的純淨水果，發揚出台灣水果的美好，而成立的一個天然手工果醬品牌......	
        <p style="float: right">
			<
			<a href="">了解更多</a>
			>
		</p> 
		</div>
	</div>
    </br>
</body>
</html>

app/views/home/content.html.erb
<body style="background-image: url(http://cdn.ypcall.com/users/B0076044-C51B-4445-BA56-2928EC583EA8/drive/media/bg.png)">
	<img style="margin-top: 0px">
	</br>
	</br>

	<div>
	<table style="font-family: Microsoft JhengHei ">
		<tr>
			<td>
				<img style="border-radius: 10px; width: 600px;"src="http://www.yooho.com.tw/images/201511/goods_img/1049_G_1447026142134.jpg">
			</td>
			<td>
				<h1 style="text-align: center">【唐婆醋】手工牛蒡醋（520ml）</h1>
				</br>

				<table>
					<tr>
						<td style="text-align: center; width: 250px; height: 30px"><b>產地</b></td>	<td>苗栗</td>
					</tr>
					<tr>
						<td style="text-align: center; width: 250px; height: 30px"><b>規格</b></td>	<td>520ml/瓶</td>
					</tr>
					<tr>
						<td style="text-align: center; width: 250px; height: 30px"><b>包裝</b></td>	<td>玻璃瓶</td>
					</tr>
					<tr>
						<td style="text-align: center; width: 250px; height: 30px"><b>保存期限</b></td>	<td>3年</td>
					</tr>
					<tr>
						<td style="text-align: center; width: 250px; height: 30px"><b>保存方法</b></td>	<td>常溫，放置陰涼處</td>
					</tr>
					<tr>
						<td style="text-align: center; width: 250px; height: 30px"><b>備註</b></td>	<td>手工釀造醋，若有沉澱純屬正常現象。</td>
					</tr>
					<tr>
						<td style="text-align: center; width: 250px; height: 30px"><b>商品售價</b></td>	<td>NT$600</td>
					</tr>
						
				</table>
				</br>

				<div style="text-align: center;">
					<button style="border-radius: 10px; height: 50px; width: 250px; margin-left: 50px; font-size: 20px; font-family: Microsoft JhengHei"><b>加入購物車</b></button>
					<button style="border-radius: 10px; height: 50px; width: 250px; margin-left: 50px; font-size: 20px; font-family: Microsoft JhengHei"><b>我要購買</b></button>
				</div>
				
				
				

			</td>
		</tr>
	</table>
	</div>
	<hr>
	<table style="font-family: Microsoft JhengHei ">
		<tr>
			<td style="width:600px">
				<h1>唐婆愛吃醋</h1>
				<img src="http://cdn.ypcall.com/users/B0076044-C51B-4445-BA56-2928EC583EA8/drive/media/tan.png" style="width:500px">
			</td>
			<td style="width: 550px;">
				<h1 style="margin-left: 70px; margin-top: 0px;">為什麼選擇唐婆醋？</h1>
				<p style="margin-left: 70px;">
					唐婆醋是以「二次發酵」菌釀轉化技術來釀造手工醋，使用的糙米及水果，均經發酵成為較小的分子，容易被人體吸收，兼具二者的養份及營養素。而一般的果醋多只是用基底醋（有些還是用合成醋）直接浸泡水果，二者之工法步驟、所需時間及品質成效均大不同！
				</p>

				<h1 style="margin-left: 70px;">好醋的功效</h1>
				<p style="width: 500px; ">
					<li style="margin-left: 70px;">調節血液的酸鹼平衡，維持弱鹼性，提高免疫力。</li>
					<li style="margin-left: 70px;">分解體內乳酸，消除疲勞、解酒。</li>
					<li style="margin-left: 70px;">刺激胃酸分泌，幫助消化。改善腸內環境，對便祕有效。</li>
					<li style="margin-left: 70px;">幫助食物中鈣質釋出，使人體容易吸收。</li>
					<li style="margin-left: 70px;">淨化血液，清除多餘膽固醇，有利降低血壓、預防心血管疾病。抑制尿酸增加，預防痛風。</li>
					<li style="margin-left: 70px;">增強肝臟機能、促進新陳代謝。分解過剩營養，預防肥胖。</li>
					<li style="margin-left: 70px;">保存食物中維他命C，可預防感冒、皮膚美白。</li>
					<li style="margin-left: 70px;">殺菌、消毒，是保健聖品。</li>
				</p>
			</td>
		</tr>
	</table>
	<hr>
	<h1 style="text-align: center; font-family: Microsoft JhengHei">
		每瓶醋都是自己的孩子──用愛心釀造的唐婆醋
	</h1>
	<div style="text-align: center">
		<img style="border-radius: 10px"src="http://www.seinsights.asia/sites/default/files/imagecache/node_main_img/upload/epaper/xiao_qi_tu_-07.jpg">
	</div>
	<div style="font-family: Microsoft JhengHei; width: 700px; margin:0px auto;">
		「醋的原始物料很重要，第一步就是友善整個社會自然環境。」唐婆醋的創始人唐婆──高沁余娓娓道出醋的故事。座落在三峽一片靜謐山林、宛如與世隔絕的白雞山莊中，唐鴉夫婦以天然的山泉水和嚴格把關的農產品為原料，親自釀製、等待發酵，歷經一整年的時間才得到一罐罐陳列在架上的「唐婆醋」，那是夫妻努力的結晶，也是兩人攜手貫徹的理念。
		<p style="float: right">
			<
			<a href="">認識唐婆醋</a>
			>
		</p>
	</div>

</body>

app/views/home/index.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
    <head>
        <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/jquery.slick/1.6.0/slick.css"/>
        <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/jquery.slick/1.6.0/slick-theme.css"/>
    </head>

    <body>
        <div class="productBig">
            <div><img src="https://scontent-tpe1-1.xx.fbcdn.net/v/t34.0-12/13235839_1448649168494334_452861147_n.png?oh=797c513c9465f54ca85ff81af8249397&oe=573D5260" style="text-align:center; width:100%; height:auto;" /></div>
            <div><img src="https://scontent-tpe1-1.xx.fbcdn.net/v/t34.0-12/13245940_1448652115160706_1539561580_n.png?oh=f07e47dfe2de0161a9c69ef2a3a44abd&oe=573E331F" style="text-align:center; width:100%; height:auto;" /></div>
            <div><img src="https://scontent-tpe1-1.xx.fbcdn.net/v/t34.0-12/13250574_1448649281827656_129256144_n.png?oh=daf52351c391f280ed9c2d56b3d5a2c6&oe=573D301B" style="text-align:center; width:100%; height:auto;" /></div>
        </div>
        <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.0/jquery.min.js"></script>
        <script type="text/javascript" src="//code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
        <script type="text/javascript" src="//cdn.jsdelivr.net/jquery.slick/1.6.0/slick.min.js"></script>
        <script type="text/javascript">
            $(document).ready(function(){
                $('.productBig').slick({
                    slidesToShow: 1,
                    slidesToScroll: 1,
                    autoplay: true,
                    autoplaySpeed: 2000,
                });
            });
        </script>
        
        <div id="css_table" style="display:table; margin-top:30px; width:100%;">
          <div class="css_tr" style="display: table-row;">
              <div class="css_td" style="display: table-cell; width:25%;">
                <a href="">
                  <img src="https://scontent-tpe1-1.xx.fbcdn.net/v/t34.0-12/13219948_1448658388493412_1331191213_n.png?oh=46afaf6a49c1c849a9a2434401a67597&oe=573D3E3A" style="width:95%;  height:220px;">
                  <p>龍眼花蜜</p>
                </a>
              </div>
              <div class="css_td" style="display: table-cell; width:25%;">
                <a href="">
                  <img src="https://scontent-tpe1-1.xx.fbcdn.net/v/t34.0-12/13228014_1448658541826730_1250870183_n.png?oh=73b82d9a7e063c3acdd2b64658c3f572&oe=573D76B7" style="width:95%; height:220px;">
                  <p>綜合果乾</p>
                </a>
              </div>
              <div class="css_td" style="display: table-cell; width:25%;">
                <a href="">
                  <img src="https://scontent-tpe1-1.xx.fbcdn.net/v/t34.0-12/13236320_1448653395160578_126456273_n.png?oh=728181437394762cfc8d5ec1a34a2aae&oe=573D079A" style="width:95%;  height:220px;">
                  <p>甜玉軒果醬</p>
                </a>
              </div>
              <div class="css_td" style="display: table-cell; width:25%;">
                <a href="">
                  <img src="https://scontent-tpe1-1.xx.fbcdn.net/v/t34.0-12/13233408_1448658188493432_1388018009_n.png?oh=3f5b2bb00c8b7c19a35b36440dfb3cb6&oe=573D541F" style="width:95%;  height:220px;">
                  <p>阿公的香水檸檬</p>
                </a>
              </div>
          </div>
          
          <div class="css_tr" style="display: table-row;">
              <div class="css_td" style="display: table-cell; width:25%;">
                <a href="">
                  <img src="https://scontent-tpe1-1.xx.fbcdn.net/v/t34.0-12/13236320_1448653395160578_126456273_n.png?oh=728181437394762cfc8d5ec1a34a2aae&oe=573D079A" style="width:95%;  height:220px;">
                  <p>甜玉軒果醬</p>
                </a>
              </div>
              <div class="css_td" style="display: table-cell; width:25%;">
                <a href="">
                  <img src="https://scontent-tpe1-1.xx.fbcdn.net/v/t34.0-12/13233408_1448658188493432_1388018009_n.png?oh=3f5b2bb00c8b7c19a35b36440dfb3cb6&oe=573D541F" style="width:95%;  height:220px;">
                  <p>阿公的香水檸檬</p>
                </a>
              </div>
              <div class="css_td" style="display: table-cell; width:25%;">
                <a href="">
                  <img src="https://scontent-tpe1-1.xx.fbcdn.net/v/t34.0-12/13219948_1448658388493412_1331191213_n.png?oh=46afaf6a49c1c849a9a2434401a67597&oe=573D3E3A" style="width:95%;  height:220px;">
                  <p>龍眼花蜜</p>
                </a>
              </div>
              <div class="css_td" style="display: table-cell; width:25%;">
                <a href="">
                  <img src="https://scontent-tpe1-1.xx.fbcdn.net/v/t34.0-12/13228014_1448658541826730_1250870183_n.png?oh=73b82d9a7e063c3acdd2b64658c3f572&oe=573D76B7" style="width:95%; height:220px;">
                  <p>綜合果乾</p>
                </a>
              </div>
          </div>
        </div>
    </body>
</html>

app/views/home/list.html.erb
<div style="margin:0px auto; margin-top:30px; width:900px; height:500px; border:2px ;">
    <%= link_to image_tag('http://cdn.ypcall.com/users/B0076044-C51B-4445-BA56-2928EC583EA8/drive/media/%E5%94%90%E5%A9%86%E9%86%8B.png'), home_content_path%>
</div>

<div style="margin:0px auto; margin-top:30px; width:900px; height:500px; border:2px ;">
    <%= link_to image_tag('http://cdn.ypcall.com/users/B0076044-C51B-4445-BA56-2928EC583EA8/drive/media/%E7%94%9C%E7%8E%89%E8%BB%922.png') %>
</div>

<div style="margin:0px auto; margin-top:30px; width:900px; height:500px; border:2px ;">
    <%= link_to image_tag('http://cdn.ypcall.com/users/B0076044-C51B-4445-BA56-2928EC583EA8/drive/media/%E5%8D%A1%E7%B6%AD%E8%98%AD.png') %>
</div>

<div style="margin:0px auto; margin-top:30px; width:900px; height:500px; border:2px ;">
    <%= link_to image_tag('http://cdn.ypcall.com/users/B0076044-C51B-4445-BA56-2928EC583EA8/drive/media/%E6%9E%9C%E9%86%AC%E5%A5%B3%E5%AD%A9.png') %>
</div>

<div style="margin:0px auto; margin-top:30px; width:900px; height:500px; border:2px ;">
    <%= link_to image_tag('http://cdn.ypcall.com/users/B0076044-C51B-4445-BA56-2928EC583EA8/drive/media/%E7%94%9C%E7%8E%89%E8%BB%922.png') %>
</div>

<div style="margin:0px auto; margin-top:30px; width:900px; height:500px; border:2px ;">
    <%= link_to image_tag('http://cdn.ypcall.com/users/B0076044-C51B-4445-BA56-2928EC583EA8/drive/media/%E9%BE%8D%E7%9C%BC%E6%9E%9C%E4%B9%BE.png') %>
</div>

app/views/layouts/_footer.html.erb
<footer style="color: #333; overflow: hidden; width: 100%; padding: 10px 0; background: #e3b968; line-height: 1.5; text-align: center;">
    Copyright © 2016 小農橋團隊. All rights reserved
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/"><img src="https://scontent-tpe1-1.xx.fbcdn.net/v/t1.0-9/13061916_1214384058574819_994569036004815320_n.jpg?oh=480c9a75a50938441bdf48064193da8b&oe=57A4C825" height="35"></a>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1" style="font-family: Microsoft JhengHei ">
      <ul class="nav navbar-nav">
        <li><%= link_to '瞧好物', home_list_path%></li>
        <li><%= link_to '瞧好農', home_blog_path %></li>
        <li><a href="">橋友手冊</a></li>
        <li><a href="">小農橋的那些事</a></li>
        <li><a href="" >結帳囉</a></li>
        <li><a href="">我要當橋友</a></li>
        <li><a href="">我是橋友</a></li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SNC001</title>
  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">
  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap-theme.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render "layouts/header" %>
<div class="container">
  <%= yield %>
</div>
<%= render "layouts/footer" %>

</body>
</html>